FROM python:3.11-slim

# System setup
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Install deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app
COPY . .

# Use env var to place the DB on a mounted volume
ENV DB_FILE=/data/bookings.db

# Railway provides $PORT; gunicorn should listen on it
ENV PORT=8000
CMD exec gunicorn -w 2 -b 0.0.0.0:$PORT app:app
